# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MCDM
                                 A QGIS plugin
 This plugin is provide facilitates to work eith vector and raster files to find a suitable place to establish solar farm in New Mexico, United States
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-02-11
        copyright            : (C) 2020 by Prasadi Senadeera
        email                : prasadisenadeera1991@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MCDM class from file MCDM.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MCDM import MCDM
    return MCDM(iface)
